Blast image
genomic-medicine-sweden/JASEN pull request #142
Opened 2023-05-31 17:31 UTC by fwa93

# Description
_##Remove elements in cursive as needed.##_

1. biopython was not installed in "pythonscripts". Therefore you got an importer error when running download_ncbi.py

2. blast did not have a singularity image and therefore it was assumed that the user had blast in their path.

_Summary of the changes made:_
1. Added a pip install biopython statement in the recepie file for biopython
2. Added a singularity image download statement in build_container.sh. modified the make_blast_db command in deploy_references:singularity.sh
## Primary function of PR
- [ x] Hotfix
- [ ] Minor functionality improvement
- [ ] Major functionality improvement / New type of analysis
- [ ] Backward-breaking functionality

# Testing
_Either describe a procedure, or add data; that confirms that the PR resolves what it sets out to do_
I ran the installation procedure again. The files created by mlst-make_blast_db.sh was now created

```
if [ -d "$saureus" ]; then echo "$saureus exists."; else echo "ERROR: $saureus does not existsaureus=${assdir}/cgmlst/staphylococcus_aureus/alleles_rereffed! Please report this to JASEN issues."; fi
/aux/db/JASEN/deploy/../assets//cgmlst/staphylococcus_aureus/alleles_rereffed exists.
if [[ -f $ref && -f $refamb && -f $refann && -f $refbwt && -f $refpac && -f $refsa ]]; then echo "bwa indexes exists."; else echo "ERROR: bwa indexes do not existref=${assdir}/genomes/staphylococcus_aureus/NC_002951.2.fasta; refamb=$ref.amb; refann=$ref.ann; refbwt=$ref.bwt; refpac=$ref.pac; refsa=$ref.sa! Please report this to JASEN issues."; fi
bwa indexes exists.
if [[ -f $mlst && -f $mlstndb && -f $mlstnhd && -f $mlstnhi && -f $mlstnhr && -f $mlstnin && -f $mlstnog && -f $mlstnos && -f $mlstnot && -f $mlstnsq && -f $mlstntf && -f $mlstnto ]]; then echo "BLAST indexes exists!"; else echo "ERROR: BLAST indexes do not existmlst=${assdir}/mlst_db/blast/mlst.fa; mlstndb=$mlst.ndb; mlstnhd=$mlst.nhd; mlstnhi=$mlst.nhi; mlstnhr=$mlst.nhr; mlstnin=$mlst.nin; mlstnog=$mlst.nog; mlstnos=$mlst.nos; mlstnot=$mlst.not; mlstnsq=$mlst.nsq; mlstntf=$mlst.ntf; mlstnto=$mlst.nto! Please report this to JASEN issues."; fi
BLAST indexes exists!

```
# Sign-offs
- [ ] Code reviewed by @octocat
- [ ] Code tested by @octocat

2023-06-01 06:38 UTC, sylvinite approved these changes
Looking good!

2023-06-01 14:49 UTC, ryanjameskennedy commented on deploy/deploy_references_singularity.sh
> +singularity exec --bind $mntroot ${containerdir}/blast.sif bash ${assdir}/mlst_db/mlst-make_blast_db.sh &> /dev/null
Nicely done!

2023-06-01 14:50 UTC, ryanjameskennedy requested changes
Just the small change to `container/build_container.sh` and it's good to go!

2023-06-02 09:48 UTC, ryanjameskennedy approved these changes

2023-06-02 09:48 UTC, merged