add Nanopore support: Flye and Medaka
genomic-medicine-sweden/jasen pull request #174
Opened 2023-09-05 11:49 UTC by Emkago

# Description
Added tools for genome assembly from Nanopore data:
- added 2 modules: Flye and Medaka
- updated config files (base and hopper)
- updated bacterial_base.nf

## Primary function of PR
- [ ] Hotfix
- [ ] Minor functionality improvement
- [x] Major functionality improvement / New type of analysis
- [ ] Backward-breaking functionality

Any suggestions how --genome-size in Flye could be defined as a parameter for each species?

# Testing
Has not been tested yet.

2023-09-05 12:01 UTC, sylvinite approved these changes
Wow nicely done! Now we're up to 3 assemblers! 💪 

It is worthwhile in the future to expand the README to make instructions for Nanopore vs others a bit more explicit.

2023-09-05 12:11 UTC, ryanjameskennedy commented on README.md
> +* Edit the `ext.args` for Medaka: specify the model with flag `-m`. Currently it is set to `r941_min_sup_g507`, but one should always set it based on how the data was produced. More about choosing th
Might be nice to do a table similar to that of Usage argumentsin line 97 for all the possible arguments. I'll make an issue and do it when I have spare time!

2023-09-05 12:19 UTC, ryanjameskennedy commented on nextflow-modules/modules/flye/main.nf
> +    tuple val(sampleName), path(reads), val(platform), val(mode)
mode needs to be removed from this input channel:)

2023-09-05 12:28 UTC, ryanjameskennedy requested changes
Everything looks great, the mode argument from flye just needs to be moved to the config:)

2023-09-06 06:24 UTC, Emkago commented on nextflow-modules/modules/flye/main.nf
> +    flye ${mode} ${reads} ${args} -o ${outputDir}
Changed ${mode} to `--nano-hq` as I it seems this is the mode that suits newly produced Nanopore data. If there is a need for a different mode, a possibility to choose a mode can be added.

Info from [Flye manual](https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#oxford-nanopore):

The default mode for regular ONT data is --nano-raw. It works well for a good range of datasets, from old R7 pores to the most recent R9.x and R10.x. The expected error rate is 10-15%.

For the most recent ONT data basecalled with Guppy5+ SUP use the new --nano-hq mode. Expected error rate is <5%.

For Q20 data, use a combination of --nano-hq and --read-error 0.03.

If you have error-corrected ONT reads (with methods such as Canu), use --nano-corr.

2023-09-06 09:54 UTC, ryanjameskennedy commented on nextflow-modules/modules/flye/main.nf
> +    flye ${mode} ${reads} ${args} -o ${outputDir}
In order for users to be able to change this easily it needs to be added to the configs under flye's configurations like this:
```
ext.args = "--nano-hq --threads 40 --genome-size 2.8m --asm-coverage 50"
```

2023-09-06 10:01 UTC, ryanjameskennedy requested changes
Just need to move the `--nano-hq` to the config external arguments.

2023-09-06 13:01 UTC, Emkago commented on nextflow-modules/modules/flye/main.nf
> +    flye ${mode} ${reads} ${args} -o ${outputDir}
Done.

2023-09-06 13:02 UTC, Emkago commented on nextflow-modules/modules/flye/main.nf
> +    flye --nano-hq ${reads} --out-dir ${outputDir} ${args}
Done.

2023-10-16 19:21 UTC, ryanjameskennedy approved these changes
LGTM!

2023-10-18 12:06 UTC, Emkago commented
> LGTM! After a quick stub-run should be good to merge!

I am on it. A run starts, but Flye and Medaka are not executed. Have to investigate why.

2024-02-26 16:10 UTC, ryanjameskennedy commented on workflows/bacterial_base.nf
> +<<<<<<< HEAD
You need to resolve this merge conflict before commiting/pushing.

2024-02-26 16:11 UTC, ryanjameskennedy requested changes
Just want to block the merging since this was approved ages ago and now does not meet the requirements.

2024-04-11 10:05 UTC, ryanjameskennedy commented on nextflow-modules/modules/medaka/main.nf
> +    // path assembly
You can remove these if they don't work

2024-04-11 10:13 UTC, ryanjameskennedy commented on nextflow-modules/modules/flye/main.nf
> +    // task.ext.when && platform == "nanopore" // process was not launched
Remove if it doesn't work

2024-04-11 10:17 UTC, ryanjameskennedy requested changes
Just a few coments. I think we should add a test csv for nanopore as well as test data. Perhaps we do that in another PR though.

2024-05-08 12:25 UTC, Emkago commented
After a few more changes in modules and base config assembly of Nanopore data works. Medaka runs two times as suggested by Amaya to get out a better assembly. I have tested it with S. aureus long-read data produced locally in our lab.

2024-05-10 06:49 UTC, sylvinite approved these changes

2024-05-14 12:56 UTC, merged