299 add qc for nanopore data
genomic-medicine-sweden/jasen pull request #344
Opened 2024-09-09 07:49 UTC by Emkago

# Description
 
Added module with NanoPlot to check quality of raw input reads produced by ONT technology.

_Summary of the changes made:_
added new module script, added container URL to Makefile, changed bacterial base workflow script

## Primary function of PR
- [ ] Hotfix
- [x] Minor functionality improvement
- [ ] Major functionality improvement / New type of analysis
- [ ] Backward-breaking functionality

# Testing
The pipeline has been run with test data, NanoPlot report is produced in the nanoplot output folder.

# Sign-offs
- [ ] Code reviewed by @octocat
- [ ] Code tested by @octocat

2024-09-09 08:31 UTC, Emkago commented
Confusion with commits, need to check what happened before reviewing and merging

2024-09-09 08:51 UTC, ryanjameskennedy commented
No worries, make it a draft until you're ready for review, so we don't use the CI resources:)

2024-09-10 07:26 UTC, ryanjameskennedy commented on configs/nextflow.base.config
> -		params.resistantLociName = 'resistance_loci'
This is necessary, please put this back:)

2024-09-10 07:27 UTC, ryanjameskennedy commented on configs/nextflow.base.config
> -	withName: add_igv_track {
Same as above, put back please:)

2024-09-10 07:30 UTC, ryanjameskennedy commented on configs/nextflow.base.config
> +	withName: nanoplot {
Can you add these to the other contigs?

2024-09-10 07:30 UTC, ryanjameskennedy commented on configs/nextflow.base.config
> -	version = '0.9.0'
Revert

2024-09-10 07:32 UTC, ryanjameskennedy requested changes
I know most of my comments are due to merging master and resolving conflict errors. Otherwise it looks good!

2024-12-11 14:24 UTC, ryanjameskennedy commented on configs/nextflow.dev.config
> +		container = "${params.containerDir}/nanoplot.sif"
```suggestion
		container ="https://depot.galaxyproject.org/singularity/nanoplot:1.43.0--pyhdfd78af_1"
```

2024-12-11 15:13 UTC, ryanjameskennedy commented on workflows/bacterial_base.nf
> +        nanoplot(ch_input_meta)
```suggestion
        nanoplot(ch_reads_w_meta)
```

2024-12-11 15:15 UTC, ryanjameskennedy commented on workflows/bacterial_base.nf
> +        nanoplot(ch_input_meta)
Check the modules that use `ch_reads_w_meta` and make sure the input channels are the same for `nanoplot`. Should work after that!

2024-12-11 15:16 UTC, ryanjameskennedy requested changes
Just one change, needs to be tested!

2024-12-20 14:29 UTC, ryanjameskennedy approved these changes
LGTM!

2025-01-14 07:51 UTC, merged