Add streptococcus workflow
genomic-medicine-sweden/jasen pull request #352
Opened 2024-09-19 17:12 UTC by ryanjameskennedy

# Description
_Summary of the changes made:_
* Add emmtyper module
* Add streptococcus profiles
* Add emmtyper to Makefile

## Primary function of PR
- [x] Major functionality improvement / New type of analysis

# Testing
Not tested

2024-10-23 13:51 UTC, ryanjameskennedy commented on Makefile
> +$(SPYO_CGMLST_DIR)/alleles_rereffed_summary_stats.tsv: $(SPYO_CGMLST_DIR)/alleles_rereffed
This shouldn't be under strep general...

2024-10-23 14:13 UTC, ryanjameskennedy commented on nextflow-modules/modules/shigapass/main.nf
> +    workflow.profile == "escherichia_coli"
Do we want to run Shigapass on `klebsiella_pneumoniae` as well?

2024-10-24 08:08 UTC, mhkc approved these changes
Looks good

2024-10-24 09:07 UTC, ryanjameskennedy commented on nextflow-modules/modules/kraken/main.nf
> +    params.useKraken
Better to put this in the config

2024-10-24 09:39 UTC, ryanjameskennedy commented on nextflow-modules/modules/bracken/main.nf
> +    params.useKraken
Better to put this in the config

2024-10-24 13:02 UTC, samuell requested changes
Great work! See comments.

2024-10-24 13:02 UTC, samuell commented on workflows/streptococcus.nf
> +        iontorrent: it[2] == "iontorrent"
Really nitpick, but wouldn't it be nice with some more indentation here?

2024-10-24 13:02 UTC, samuell commented on workflows/streptococcus_pyogenes.nf
> +        iontorrent: it[2] == "iontorrent"
Same here: Would be prettier (and a tad bit more readable) with an extra indentation step here.

2024-10-24 13:49 UTC, ryanjameskennedy commented on configs/nextflow.dev.config
> +	containerDir = "/fs1/resources/containers"
Nope we've moved our containers to a general place so that we don't have duplicates for `jasen` and `jasen_dev`

2024-10-24 13:50 UTC, ryanjameskennedy commented on nextflow-modules/modules/serotypefinder/main.nf
> +    workflow.profile != "mycobacterium_tuberculosis" && workflow.profile != "streptococcus" && workflow.profile != "streptococcus_pyogenes"
Nice!

2024-10-25 08:44 UTC, merged